-- ERROR [집계 함수 이외의 컬럼은 프로젝션 될 수 없다.]
-- SELECT EMPLOYEE_ID, AVG(SALARY), MAX(SALARY)
-- FROM EMPLOYEES;

-- 단, GROUP BY 절에 참여 하고 있는 컬럼은 프로젝션 할 수 있다.
SELECT JOB_ID, AVG(SALARY), MAX(SALARY)
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY JOB_ID
HAVING AVG(SALARY) > 5000
ORDER BY AVG(SALARY);
