-- MATH

SELECT ABS (-1) FROM DUAL; --절대값

SELECT CEIL (4.122) FROM DUAL;

SELECT FLOOR (3.9012) FROM DUAL;

SELECT ROUND (3.3364, 2) FROM DUAL;

SELECT MOD (99, 4) FROM DUAL;

SELECT POWER (22, 4) FROM DUAL;

SELECT TRUNC(3.3864, 1) FROM DUAL;

SELECT SIGN(-22) FROM DUAL; --음수 체크

-- DATE

SELECT value 
  FROM nls_session_parameters 
 WHERE parameter = 'NLS_DATE_FORMAT';
 
 SELECT EMPLOYEE_ID AS "ID" , HIRE_DATE FROM EMPLOYEES;
 
 SELECT ADD_MONTHS(SYSDATE, 3) FROM DUAL;
 SELECT ADD_MONTHS('15/01/01', 3) FROM DUAL;
 SELECT ADD_MONTHS('2015-01-01', 3) FROM DUAL;
 
 SELECT LAST_DAY(SYSDATE) FROM DUAL;
 SELECT LAST_DAY('2015-02-22') FROM DUAL;
 
 SELECT MONTHS_BETWEEN(ADD_MONTHS(SYSDATE,3 ), SYSDATE) FROM DUAL;
 
 SELECT EMPLOYEE_ID, JOB_ID, ROUND(MONTHS_BETWEEN(END_DATE, START_DATE))
 FROM JOB_HISTORY;
 
 -- 요일
 SELECT NEXT_DAY(SYSDATE, 7) FROM DUAL;
 
 
 -- 숫자 <--> 문자
 
 SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES;
 
 SELECT EMPLOYEE_ID, TO_CHAR(SALARY,'9999') 
 FROM EMPLOYEES;
 
 SELECT EMPLOYEE_ID, TO_CHAR(SALARY,'9999999999') 
 FROM EMPLOYEES;
 
SELECT EMPLOYEE_ID, TO_CHAR(SALARY,'00009999') 
FROM EMPLOYEES;
 
SELECT EMPLOYEE_ID, TO_CHAR(SALARY,'999,999,999') 
FROM EMPLOYEES;
 
SELECT TO_CHAR(3.14143453, '9.99') FROM DUAL;
 
 
 
SELECT EMPLOYEE_ID, TO_CHAR(SALARY,'FM999999999') 
FROM EMPLOYEES;
 
SELECT EMPLOYEE_ID, TO_CHAR(SALARY,'FML999999999') 
FROM EMPLOYEES;
 
SELECT TO_CHAR(-12345, '99999MI') FROM DUAL;
SELECT TO_CHAR(-12345, 'S99999') FROM DUAL;
  
SELECT TO_NUMBER('123456','9999999') FROM DUAL;
SELECT TO_NUMBER('123456','9999999')+100 FROM DUAL;
 
 
 
 --DATE <-> 문자열
 
 SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'YYYY-MM-DD HH:MI:SS') FROM EMPLOYEES;
 SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'YYYY-MM-DD PM HH:MI:SS') FROM EMPLOYEES;
 SELECT EMPLOYEE_ID, TO_CHAR(HIRE_DATE,'YYYY-MM-DD DAY PM HH:MI:SS') FROM EMPLOYEES;
 SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD DDD"일째 되는날" PM HH:MI:SS') FROM DUAL;
 SELECT TO_CHAR(SYSDATE,'RR') FROM DUAL;
 
 -- 현재 세기(2000)
 SELECT TO_CHAR(TO_DATE('30','RR'),'YYYY') FROM DUAL;
 -- 이전 세기(1900)
 SELECT TO_CHAR(TO_DATE('60','RR'),'YYYY') FROM DUAL;
 
 
 