-- 다시 풀어보기
-- 1-1)
SELECT CONCAT(FIRST_NAME, CONCAT(' ',LAST_NAME)), SALARY, PHONE_NUMBER
FROM EMPLOYEES
ORDER BY HIRE_DATE;

-- 1-2)
SELECT JOB_TITLE, MAX_SALARY
FROM JOBS
ORDER BY MAX_SALARY DESC;

-- 1-3)
SELECT COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;

-- 1-4)
SELECT JOB_TITLE
FROM JOBS
ORDER BY MAX_SALARY DESC;

-- 1-5)
SELECT COUNT(DEPARTMENT_ID)
FROM DEPARTMENTS;

-- 1-6)
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
ORDER BY LENGTH(DEPARTMENT_NAME) DESC;

-- 1-7)
SELECT COUNT(DEPARTMENT_ID)
FROM DEPARTMENTS
WHERE MANAGER_ID IS NULL;

-- 1-8)
SELECT UPPER(COUNTRY_NAME)
FROM COUNTRIES
ORDER BY COUNTRY_NAME;

-- 1-9)
SELECT REGION_ID
FROM REGIONS
ORDER BY REGION_NAME;

-- 1-10)
SELECT DISTINCT LOWER(CITY)
FROM LOCATIONS
ORDER BY LOWER(CITY) ASC;